//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorVisualisation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorVisualisation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Population Visualisation.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string BitmapHeight {
            get {
                return ResourceManager.GetString("BitmapHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string BitmapWidth {
            get {
                return ResourceManager.GetString("BitmapWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover Type.
        /// </summary>
        public static string CrossoverType {
            get {
                return ResourceManager.GetString("CrossoverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96.
        /// </summary>
        public static string DPI {
            get {
                return ResourceManager.GetString("DPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation Rate.
        /// </summary>
        public static string MutationRate {
            get {
                return ResourceManager.GetString("MutationRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation Type.
        /// </summary>
        public static string MutationType {
            get {
                return ResourceManager.GetString("MutationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visualisation.
        /// </summary>
        public static string NewVisualisation {
            get {
                return ResourceManager.GetString("NewVisualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string NumberOfValuesInPixel {
            get {
                return ResourceManager.GetString("NumberOfValuesInPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseVisualisation {
            get {
                return ResourceManager.GetString("PauseVisualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartVisualisation {
            get {
                return ResourceManager.GetString("RestartVisualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Type.
        /// </summary>
        public static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartVisualisation {
            get {
                return ResourceManager.GetString("StartVisualisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualisation Speed.
        /// </summary>
        public static string VisualisationSpeed {
            get {
                return ResourceManager.GetString("VisualisationSpeed", resourceCulture);
            }
        }
    }
}
